import { Injectable } from "@angular/core";

@Injectable()

export class RiskAnalysisService {

    getRiskAnalysis() {
        return [
           
            {
                "portfolio": "Total Fund",
                "benchmark": "Total Fund Relative Objective*",
                "alpha": -.35,
                "beta": 1.05,
                "corrCo": .99,
                "infoRatio": -.03,
                "sharpeRatio": ".77 / .81" ,
            },
            {
                "portfolio": "Dodge & Cox Equity",
                "benchmark": "S&P 500",
                "alpha": -2.81,
                "beta": 1.15,
                "corrCo": .97,
                "infoRatio": -.34,
                "sharpeRatio": ".71 / .93",
            },
            {
                "portfolio": "",
                "benchmark": "Russell 1000 Value",
                "alpha": -.69,
                "beta": 1.07,
                "corrCo": .97,
                "infoRatio": -.04,
                "sharpeRatio": ".71 / .78",
            },
            {
                "portfolio": "SIT Inv. Associates",
                "benchmark": "S&P 500",
                "alpha": -.22,
                "beta": .97,
                "corrCo": .98,
                "infoRatio": -.23,
                "sharpeRatio": ".89 / .93",
            },
            {
                "portfolio": "",
                "benchmark": "Russell 1000 Growth",
                "alpha": -1.12,
                "beta": .98,
                "corrCo": .99,
                "infoRatio": -1.08,
                "sharpeRatio": ".89 / .98",
            },
            {
                "portfolio": "Fiduciary Management",
                "benchmark": "Russell 2000",
                "alpha": "n/a",
                "beta": "n/a",
                "corrCo": "n/a",
                "infoRatio": "n/a",
                "sharpeRatio": "n/a",
            },
            {
                "portfolio": "",
                "benchmark": "Russell 2000 Value",
                "alpha": "n/a",
                "beta": "n/a",
                "corrCo": "n/a",
                "infoRatio": "n/a",
                "sharpeRatio": "n/a",
            },
            {
                "portfolio": "Morgan Stanley - International Equity",
                "benchmark": "MSCI ACWI Ex-US",
                "alpha": 3.02,
                "beta": .89,
                "corrCo": .98,
                "infoRatio": .94,
                "sharpeRatio": ".31 / .09",
            },
            {
                "portfolio": "",
                "benchmark": "MSCI EAFE",
                "alpha": 1.24,
                "beta": .90,
                "corrCo": .99,
                "infoRatio": .42,
                "sharpeRatio": ".31 / .22",
            },
            {
                "portfolio": "Lazard Asset Management",
                "benchmark": "MSCI ACWI Ex-US",
                "alpha": "n/a",
                "beta": "n/a",
                "corrCo": "n/a",
                "infoRatio": "n/a",
                "sharpeRatio": "n/a",
            },
            {
                "portfolio": "",
                "benchmark": "MSCI EAFE",
                "alpha": "n/a",
                "beta": "n/a",
                "corrCo": "n/a",
                "infoRatio": "n/a",
                "sharpeRatio": "n/a",
            },
            {
                "portfolio": "Morgan Stanley - Emerging Markets Equity",
                "benchmark": "MSCI ACWI Ex-US",
                "alpha": -2.14,
                "beta": .94,
                "corrCo": .94,
                "infoRatio": -.43,
                "sharpeRatio": "-.06 / .09",
            },
            {
                "portfolio": "",
                "benchmark": "MSCI Emerging Markets",
                "alpha": 1.47,
                "beta": .85,
                "corrCo": .99,
                "infoRatio": .66,
                "sharpeRatio": "-.06 / -.16",
            },
            {
                "portfolio": "Loomis Sayles Co.",
                "benchmark": "Barclays Aggregate",
                "alpha": 1.33,
                "beta": .86,
                "corrCo": .70,
                "infoRatio": .31,
                "sharpeRatio": "1.22 / 1.23",
            },
            {
                "portfolio": "RREEF II & III",
                "benchmark": "NCREIF ODCE",
                "alpha": -1.77,
                "beta": 1.37,
                "corrCo": .57,
                "infoRatio": 1.59,
                "sharpeRatio": "6.80 / 13.61",
            },
            {
                "portfolio": "",
                "benchmark": "NSCREIF Property",
                "alpha": -1.80,
                "beta": 1.38,
                "corrCo": .57,
                "infoRatio": 1.58,
                "sharpeRatio": "6.80 / 13.70",
            },
            {
                "portfolio": "Tortoise Capital Advisors",
                "benchmark": "SP MLP",
                "alpha": "n/a",
                "beta": "n/a",
                "corrCo": "n/a",
                "infoRatio": "n/a",
                "sharpeRatio": "n/a",
            },
            {
                "portfolio": "Natural Resources VIII",
                "benchmark": "Big CF Natl Res VIII",
                "alpha": -6.59,
                "beta": .75,
                "corrCo": .64,
                "infoRatio": -1.04,
                "sharpeRatio": ".10 / 1.03",
            },
            {
                "portfolio": "UBS Neutral Alpha Strategies",
                "benchmark": "HFR FOF Conservative",
                "alpha": "n/a",
                "beta": "n/a",
                "corrCo": "n/a",
                "infoRatio": "n/a",
                "sharpeRatio": "n/a",
            }
        ]
    }
}
