let data = [

        {
            "type": "Domestic Equity",
            "prevEquities": 97.4,
            "curntEquities": 97.5,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": 2.6,
            "curntCash": 2.5,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 27.8,
            "curntValue": 41.7
        },
        {
            "type": "    Core",
            "prevEquities": 99.2,
            "curntEquities": 98.9,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": 0.8,
            "curntCash": 1.1,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 22.3,
            "curntValue": 33.5
        },
        {
            "type": "       Dodge & Cox Equity",
            "prevEquities": 100.0,
            "curntEquities": 100.0,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": NaN,
            "curntCash": NaN,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 10.9,
            "curntValue": 16.4
        },
        {
            "type": "       SIT Inv. Associates",
            "prevEquities": 98.7,
            "curntEquities": 97.8,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": 1.3,
            "curntCash": NaN,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 11.4,
            "curntValue": 17.1
        },
        {
            "type": "    Specialty Small",
            "prevEquities": 87.6,
            "curntEquities": 91.7,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": 12.4,
            "curntCash": 8.3,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 5.5,
            "curntValue": 8.3
        },
        {
            "type": "       Fiduciary Management",
            "prevEquities": 87.6,
            "curntEquities": 91.7,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": 12.4,
            "curntCash": 8.3,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 5.5,
            "curntValue": 8.3
        },
        {
            "type": "International Equity",
            "prevEquities": 100.0,
            "curntEquities": 100.0,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": NaN,
            "curntCash": NaN,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 28.9,
            "curntValue": 43.3
        },
        {
            "type": "    Large Cap",
            "prevEquities": 100.0,
            "curntEquities": 100.0,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": NaN,
            "curntCash": NaN,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 22.8,
            "curntValue": 34.3
        },
        {
            "type": "       Morgan Stanley - International Equity",
            "prevEquities": 100.0,
            "curntEquities": 100.0,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": NaN,
            "curntCash": NaN,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 9.0,
            "curntValue": 13.5
        },
        {
            "type": "       Lazard Asset Management",
            "prevEquities": 100.0,
            "curntEquities": 100.0,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": NaN,
            "curntCash": NaN,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 13.8,
            "curntValue": 20.8
        },
        {
            "type": "    Emerging Markets",
            "prevEquities": 100.0,
            "curntEquities": 100.0,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": NaN,
            "curntCash": NaN,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 6.0,
            "curntValue": 9.0
        },
        {
            "type": "       Morgan Stanley - Emerging Markets",
            "prevEquities": 100.0,
            "curntEquities": 100.0,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": NaN,
            "curntCash": NaN,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 6.0,
            "curntValue": 9.0
        },
        {
            "type": "Domestic Fixed Income",
            "prevEquities": NaN,
            "curntEquities": NaN,
            "prevFixed": 100.0,
            "curntFixed": 100.0,
            "prevCash": NaN,
            "curntCash": NaN,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 15.6,
            "curntValue": 23.5
        },
        {
            "type": "    Intermediate Term",
            "prevEquities": NaN,
            "curntEquities": NaN,
            "prevFixed": 100.0,
            "curntFixed": 100.0,
            "prevCash": NaN,
            "curntCash": NaN,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 15.6,
            "curntValue": 23.5
        },
        {
            "type": "       Loomis Sayles Co.",
            "prevEquities": NaN,
            "curntEquities": NaN,
            "prevFixed": 100.0,
            "curntFixed": 100.0,
            "prevCash": NaN,
            "curntCash": NaN,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 15.6,
            "curntValue": 23.5
        },
        {
            "type": "Domestic Real Estate",
            "prevEquities": NaN,
            "curntEquities": NaN,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": NaN,
            "curntCash": NaN,
            "prevOther": 100.0,
            "curntOther": 100.0,
            "pcntoftotal": 8.6,
            "curntValue": 13.0
        },
        {
            "type": "       RREEF II & III",
            "prevEquities": NaN,
            "curntEquities": NaN,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": NaN,
            "curntCash": NaN,
            "prevOther": 100.0,
            "curntOther": 100.0,
            "pcntoftotal": 8.6,
            "curntValue": 13.0
        },
        {
            "type": "Domestic Energy Infrastructure",
            "prevEquities": NaN,
            "curntEquities": 100.0,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": NaN,
            "curntCash": NaN,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 4.7,
            "curntValue": 7.1
        },
        {
            "type": "      Tortoise Capital Advisors",
            "prevEquities": NaN,
            "curntEquities": 100.0,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": NaN,
            "curntCash": NaN,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 4.7,
            "curntValue": 7.1
        },
        {
            "type": "Domestic Commodities",
            "prevEquities": 100.0,
            "curntEquities": 100.0,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": NaN,
            "curntCash": NaN,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 0.4,
            "curntValue": 0.6
        },
        {
            "type": "       Natural Resources VIII",
            "prevEquities": 100.0,
            "curntEquities": 100.0,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": NaN,
            "curntCash": NaN,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 0.4,
            "curntValue": 0.6
        },
        {
            "type": "Domestic Hedge Funds",
            "prevEquities": NaN,
            "curntEquities": NaN,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": NaN,
            "curntCash": NaN,
            "prevOther": 100.0,
            "curntOther": 100.0,
            "pcntoftotal": 8.0,
            "curntValue": 12.1
        },
        {
            "type": "       UBS Neutral Alpha Strategies",
            "prevEquities": NaN,
            "curntEquities": NaN,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": NaN,
            "curntCash": NaN,
            "prevOther": 100.0,
            "curntOther": 100.0,
            "pcntoftotal": 8.0,
            "curntValue": 12.1
        },
        {
            "type": "Domestic Private Equity",
            "prevEquities": 100.0,
            "curntEquities": 100.0,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": NaN,
            "curntCash": NaN,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 5.0,
            "curntValue": 7.5
        },
        {
            "type": "       Abbott Capital Private Equity",
            "prevEquities": 100.0,
            "curntEquities": 100.0,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": NaN,
            "curntCash": NaN,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 3.1,
            "curntValue": 4.7
        },
        {
            "type": "       Commonfund Intl PE VII",
            "prevEquities": 100.0,
            "curntEquities": 100.0,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": NaN,
            "curntCash": NaN,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 0.6,
            "curntValue": 0.8
        },
        {
            "type": "       Commonfund VP IX",
            "prevEquities": 100.0,
            "curntEquities": 100.0,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": NaN,
            "curntCash": NaN,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 0.6,
            "curntValue": 0.9
        },
        {
            "type": "       Commonfund PE VIII",
            "prevEquities": 100.0,
            "curntEquities": 100.0,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": NaN,
            "curntCash": NaN,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 0.3,
            "curntValue": 0.4
        },
        {
            "type": "       Commonfund Capital Partners V",
            "prevEquities": 100.0,
            "curntEquities": 100.0,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": NaN,
            "curntCash": NaN,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 0.4,
            "curntValue": 0.6
        },
        {
            "type": "Domestic Cash",
            "prevEquities": NaN,
            "curntEquities": NaN,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": 100.0,
            "curntCash": 100.0,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 0.9,
            "curntValue": 1.4
        },
        {
            "type": "       Cash Account",
            "prevEquities": NaN,
            "curntEquities": NaN,
            "prevFixed": NaN,
            "curntFixed": NaN,
            "prevCash": 100.0,
            "curntCash": 100.0,
            "prevOther": NaN,
            "curntOther": NaN,
            "pcntoftotal": 0.9,
            "curntValue": 1.4
        }
    ]

localStorage.setItem('data', JSON.stringify(data));
